// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadNetworkTracker returns the embedded CollectionSpec for NetworkTracker.
func LoadNetworkTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkTrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetworkTracker: %w", err)
	}

	return spec, err
}

// LoadNetworkTrackerObjects loads NetworkTracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetworkTrackerObjects
//	*NetworkTrackerPrograms
//	*NetworkTrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetworkTrackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetworkTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetworkTrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkTrackerSpecs struct {
	NetworkTrackerProgramSpecs
	NetworkTrackerMapSpecs
	NetworkTrackerVariableSpecs
}

// NetworkTrackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkTrackerProgramSpecs struct {
	HandleSetState *ebpf.ProgramSpec `ebpf:"handle_set_state"`
}

// NetworkTrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkTrackerMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// NetworkTrackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkTrackerVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// NetworkTrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkTrackerObjects struct {
	NetworkTrackerPrograms
	NetworkTrackerMaps
	NetworkTrackerVariables
}

func (o *NetworkTrackerObjects) Close() error {
	return _NetworkTrackerClose(
		&o.NetworkTrackerPrograms,
		&o.NetworkTrackerMaps,
	)
}

// NetworkTrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkTrackerMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *NetworkTrackerMaps) Close() error {
	return _NetworkTrackerClose(
		m.Events,
	)
}

// NetworkTrackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkTrackerVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// NetworkTrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkTrackerPrograms struct {
	HandleSetState *ebpf.Program `ebpf:"handle_set_state"`
}

func (p *NetworkTrackerPrograms) Close() error {
	return _NetworkTrackerClose(
		p.HandleSetState,
	)
}

func _NetworkTrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed networktracker_bpfel.o
var _NetworkTrackerBytes []byte
