// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cluster-agent/internal"
	"cluster-agent/internal/api/handlers"
	"cluster-agent/internal/config"
	"cluster-agent/internal/consumers"
	"cluster-agent/internal/k8s"
	"cluster-agent/internal/producers"
	"cluster-agent/internal/services"
	"cluster-agent/internal/services/topology"
	"k8s.io/client-go/informers"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/cache"
	"time"
)

// Injectors from wire.go:

func InitializeApp() (*internal.App, error) {
	client, err := k8s.NewClient()
	if err != nil {
		return nil, err
	}
	kubernetesInterface := ProvideK8sInterface(client)
	podService := services.NewPodService(kubernetesInterface)
	podHandler := handlers.NewPodHandler(podService)
	deploymentService := services.NewDeploymentService(kubernetesInterface)
	deploymentHandler := handlers.NewDeploymentHandler(deploymentService)
	namespaceService := services.NewNamespaceService(kubernetesInterface)
	namespaceHandler := handlers.NewNamespaceHandler(namespaceService)
	kubernetesServiceService := services.NewServiceService(kubernetesInterface)
	serviceHandler := handlers.NewServiceHandler(kubernetesServiceService)
	nodeService := services.NewNodeService(kubernetesInterface)
	nodeHandler := handlers.NewNodeHandler(nodeService)
	restConfig := ProvideRestConfig(client)
	terminalService := services.NewTerminalService(kubernetesInterface, restConfig)
	terminalHandler := handlers.NewTerminalHandler(terminalService)
	service := topology.NewTopologyService()
	sharedInformerFactory := ProvideInformerFactory(kubernetesInterface)
	snapshotService := services.NewSnapshotService(sharedInformerFactory)
	topologyHandler := handlers.NewTopologyHandler(service, snapshotService)
	podLogsService := services.NewPodLogsService(kubernetesInterface)
	podLogsHandler := handlers.NewPodLogsHandler(podLogsService)
	configMapService := services.NewConfigMapService(kubernetesInterface)
	configMapHandler := handlers.NewConfigMapHandler(configMapService)
	secretService := services.NewSecretService(kubernetesInterface)
	secretHandler := handlers.NewSecretHandler(secretService)
	ingressService := services.NewIngressService(kubernetesInterface)
	ingressHandler := handlers.NewIngressHandler(ingressService)
	pvcService := services.NewPVCService(kubernetesInterface)
	pvcHandler := handlers.NewPvcHandler(pvcService)
	handlerContainer := handlers.NewHandlerContainer(podHandler, deploymentHandler, namespaceHandler, serviceHandler, nodeHandler, terminalHandler, topologyHandler, podLogsHandler, configMapHandler, secretHandler, ingressHandler, pvcHandler)
	configConfig := config.NewConfig()
	eventBatcher := consumers.NewEventBatcher(configConfig)
	sharedIndexInformer := ProvideEventInformer(sharedInformerFactory)
	eventCollector := producers.NewEventCollector(eventBatcher, sharedIndexInformer)
	app := internal.NewApp(handlerContainer, eventCollector, eventBatcher, sharedInformerFactory)
	return app, nil
}

// wire.go:

func ProvideK8sInterface(client *k8s.Client) kubernetes.Interface {
	return client.GetClientset()
}

func ProvideRestConfig(client *k8s.Client) *rest.Config {
	return client.GetConfig()
}

func ProvideInformerFactory(clientset kubernetes.Interface) informers.SharedInformerFactory {
	return informers.NewSharedInformerFactory(clientset, 12*time.Hour)
}

func ProvideEventInformer(factory informers.SharedInformerFactory) cache.SharedIndexInformer {
	return factory.Core().V1().Events().Informer()
}
