// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cluster-agent/internal"
	"cluster-agent/internal/api/handlers"
	"cluster-agent/internal/config"
	"cluster-agent/internal/consumers"
	"cluster-agent/internal/k8s"
	"cluster-agent/internal/producers"
	"cluster-agent/internal/services"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)

// Injectors from wire.go:

func InitializeApp() (*internal.App, error) {
	client, err := k8s.NewClient()
	if err != nil {
		return nil, err
	}
	kubernetesInterface := ProvideK8sInterface(client)
	podService := services.NewPodService(kubernetesInterface)
	podHandler := handlers.NewPodHandler(podService)
	deploymentService := services.NewDeploymentService(kubernetesInterface)
	deploymentHandler := handlers.NewDeploymentHandler(deploymentService)
	namespaceService := services.NewNamespaceService(kubernetesInterface)
	namespaceHandler := handlers.NewNamespaceHandler(namespaceService)
	kubernetesServiceService := services.NewServiceService(kubernetesInterface)
	serviceHandler := handlers.NewServiceHandler(kubernetesServiceService)
	nodeService := services.NewNodeService(kubernetesInterface)
	nodeHandler := handlers.NewNodeHandler(nodeService)
	restConfig := ProvideRestConfig(client)
	terminalService := services.NewTerminalService(kubernetesInterface, restConfig)
	terminalHandler := handlers.NewTerminalHandler(terminalService)
	handlerContainer := handlers.NewHandlerContainer(podHandler, deploymentHandler, namespaceHandler, serviceHandler, nodeHandler, terminalHandler)
	configConfig := config.NewConfig()
	eventBatcher := consumers.NewEventBatcher(configConfig)
	eventCollector := producers.NewEventCollector(kubernetesInterface, eventBatcher)
	app := internal.NewApp(handlerContainer, eventCollector, eventBatcher)
	return app, nil
}

// wire.go:

func ProvideK8sInterface(client *k8s.Client) kubernetes.Interface {
	return client.GetClientset()
}

func ProvideRestConfig(client *k8s.Client) *rest.Config {
	return client.GetConfig()
}
